<?php


namespace app\models;


class RecipeLike extends \rhosocial\base\models\models\BaseBlameableModel
{
    public $hostClass = User::class;
    public $contentAttribute = null;
    public $idAttributeType = 0;
    public $idAttribute = null;
    public $createdAtAttribute = null;
    public $updatedAtAttribute = null;
    public $ipAttribute = null;
    public $ipTypeAttribute = null;
    public $enableIP = 0;
    public static function tableName()
    {
        return "{{%liked_recipe}}"; // TODO: Change the autogenerated stub
    }
}