<?php


namespace app\models;


class RecipeStep extends \rhosocial\base\models\models\BaseBlameableModel
{
    public $hostClass = Recipe::class;
    public $contentAttribute = null;
    public $idAttributeType = 0;
    public $idAttribute = null;
    public $createdByAttribute = 'recipe_guid';
    public $updatedByAttribute='recipe_guid';
    public $createdAtAttribute = null;
    public $updatedAtAttribute = null;
    public $ipAttribute = null;
    public $enableIP = 0;
    public static function tableName()
    {
        return "{{%recipe_step}}"; // TODO: Change the autogenerated stub
    }
}